### ISSUE TITLE
Running sbt assembly on the root project generates more assemblies than expected

### ISSUE THREAD

**Issue by aneesh-joseph** [pbassiner/sbt-multi-project-example#3]
First of all thank you for the detailed tutorial and this multimodule sample :smile:

When I run sbt assembly on the top level directory, it generates multiple assemblies

1. common-assembly-0.1-SNAPSHOT.jar
2. multi1.jar
3. multi2.jar
4. sbt-multi-project-example-assembly-0.1-SNAPSHOT.jar

but I was only expecting assemblies for multi1 and multi2 projects. Is there a way to sort it?

In addition to that, is it possible to attach these assemblies so that the assemblies can be published to Nexus etc?

**Comment by pbassiner** [comment]
Hi @aneesh-joseph,
I'm glad you find it useful.

Regarding your questions, you can disable the `sbt-assembly` plugin in those subprojects (root & common) by adding `.disablePlugins(AssemblyPlugin)` to each one of them.

On the other hand, publishing fat jars is not recommended but if you really need to, there are some guidelines in the [sbt-assembly README](https://github.com/sbt/sbt-assembly/#publishing-not-recommended).

Cheers!
