### ISSUE TITLE
Running tests in all sub-projects

### ISSUE THREAD

**Issue by lewisjkl** [pbassiner/sbt-multi-project-example#4]
Thank you for putting up this example, it has been super helpful.

How would you go about running all tests from all sub-projects with one SBT command? I am trying to run all tests in a CI/CD pipeline.

**Comment by pbassiner** [comment]
Hi @lewisjkl,
I'm glad you find it useful, thanks.
Regarding your question, running the `test` task from the root project will run all tests from all sub-projects since the root project is aggregating all sub-projects.

Best

**Comment by lewisjkl** [comment]
Thank you for your timely response! It doesn't seem like this is working for me, however I think that my issue is stemming from the fact that I actually am using `dependsOn` instead of `aggregates` because I need to be able to access some parts of the submodules from the top level task. I will have to experiment and see what I can come up with for this.

**Comment by pbassiner** [comment]
Hi @lewisjkl,
if that's the case, you should do both `dependsOn` and `aggregates`.

**Comment by lewisjkl** [comment]
@pbassiner thanks for the tip! I wasn't sure if that would be redundant or not so thank you for your clarification.
