### ISSUE TITLE
Scalastyle on all sub-projects

### ISSUE THREAD

**Issue by lewisjkl** [pbassiner/sbt-multi-project-example#5]
I've seen some issues related to this in the scalastyle repo, but I wondered if you have had any success with it since I saw the dependency in your `project/plugins.sbt` file. How would you go about configuring ScalaStyle so it would check all of your subprojects?

**Comment by pbassiner** [comment]
Hi @lewisjkl,
as in #4, running `scalastyle` in the root project, will run it for all the aggregated sub-projects. Take into account that you need a `scalastyle_config.xml` file in the root path of the project. You can check out its documentation [here](http://www.scalastyle.org/configuration.html).

Best
