### ISSUE TITLE
Running "sbt" fails with IncompatiblePluginsException

### ISSUE THREAD

**Issue by sschuberth** [pbassiner/sbt-multi-project-example#6]
I was running "sbt" on a fresh clone (on Windows 10 with Java 9) and got:

```
[info] Loading settings from plugins.sbt ...
[info] Loading project definition from C:\Users\sebastian\Development\GitHub\sbt                                                 -multi-project-example\project
[error] sbt.internal.IncompatiblePluginsException: Binary incompatibility in plu                                                 gins detected.
[error] Note that conflicts were resolved for some dependencies:
[error]         org.codehaus.plexus:plexus-utils
[error]         io.get-coursier:coursier-cache_2.12
[error]         io.get-coursier:coursier_2.12
[error]         org.scala-lang.modules:scala-parser-combinators_2.12
[error]         org.scala-sbt:librarymanagement-core_2.12
[error]         org.slf4j:slf4j-api
[error]         org.scala-sbt:util-tracking_2.12
[error]         org.scala-sbt:util-cache_2.12
[error]         org.scala-sbt:util-logging_2.12
[error]         org.scala-sbt:util-interface
[error]         org.scala-sbt:util-control_2.12
[error]         org.scala-sbt:io_2.12
[error]         org.scala-lang.modules:scala-xml_2.12
[error]         org.scala-sbt:util-relation_2.12
[error]         org.scala-sbt:util-position_2.12
...
```

**Comment by pbassiner** [comment]
Hi @sschuberth,
I ain't got a Windows system I can use to test it but, which sbt & scala version are you using? I think the message you're seeing states that some sbt plugins are binary incompatible with the scala version you're using.

**Comment by sschuberth** [comment]
I'm using Scala 2.12. But isn't the sbt version determined by your [build.properties](https://github.com/pbassiner/sbt-multi-project-example/blob/master/project/build.properties) anyway?

**Comment by pbassiner** [comment]
Right.
Then I would create an empty project with all these plugins, and iteratively remove them to find out the offending one.
I've never run into this kind of error. For what I understand, it means sbt and the plugin are built against binary incompatible Scala versions. Maybe using Java9 has something to do with it? I've never run sbt/Scala with Java9 so I can't tell whether it should work or not.
